### ISSUE TITLE
File Missing and Projects not working on IAR

### ISSUE THREAD

**Issue by Alex-ARO-WT** [STMicroelectronics/STM32CubeH5#1]
Hello, 
I'm working on NUCLEO-H563ZI/Examples/GPIO/GPIO_IOToggle_TrustZone.
I downloaded this example from STM32CubeMX

My set-up :
NUCLEO-H563ZI 
IAR embedded Workbench for ARM 9.32.2.57414
IAR embedded Workbench shared components 9.1.8.10480

Bug Description :
When I build the program, I have errors like this :
"'.../Src/main.c', needed by '......./main.o', missing and no known rule to make it	"
In the file tree, if I double clic on main file, it is missing.

So, after adding all missing file, I can build both program.
When I try to download it with “xxxxx_S” as active application I have error :
"Multiple images overlap (at address range 0xC000000 - 0xC001988)

Thus, I try to download it with "xxxxx_NS" as active application, the program freeze on "SECURE_RegisterCallback" function un the main.c file.

Thank you

**Comment by TOUNSTM** [comment]
Hello @TOUNSTM,

Thank you for this report. We will get back to you as soon as we analyze it further. This may take some time. Thank you for your comprehension.

With regards,

**Comment by TOUNSTM** [comment]
Hello @Alex-ARO-WT,

Thank you for this report. We will get back to you as soon as we analyze it further. This may take some time. Thank you for your comprehension.

With regards,

**Comment by TOUNSTM** [comment]
Hello @Alex-ARO-WT,

Thank you for your report. This point is related to the CubeMX generation problem and not directly related to the firmware published in this repository.
We tried to reproduce the issue you have described in [#1](https://github.com/STMicroelectronics/STM32CubeH5/issues/1) using STM32CubeMx v6.11.1, with no success.
Now, as this issue is not directly related to some software component published within this repository (CMSIS, HAL, BSP, etc.) but rather to our ecosystem (namely the Cube MX tool), please allow me to close it.

In case you have other CubeMX-related issues to share, please submit them in the [ST Community](
https://community.st.com/s/question/0D53W00000JhsU4SAJ/stm32cubemx-ide-issue-throws-warning-when-using-macros)
in the CubeMX related section. There you shall find people who will address your request and whom you will hopefully find a solution with.

Thank you again for your report. We are looking forward to reading from you again.

With regards,
